import { Geist, Geist_Mono } from "next/font/google";
import "../style/index.css";
import "../style/app.css";
import '@fortawesome/fontawesome-free/css/all.min.css';
import 'alertifyjs/build/css/alertify.css';
import 'alertifyjs/build/css/themes/default.css';
import "../style/all.min.css"
import Script from "next/script";
import Skeleton from 'react-loading-skeleton'
import 'react-loading-skeleton/dist/skeleton.css'
import Nav from "@/Components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <head>
        {/* اسکریپت یکتانت */}
        <Script id="yektanet" strategy="beforeInteractive">
          {`
            !function(e,t,n){
              e.yektanetAnalyticsObject=n,
              e[n]=e[n]||function(){e[n].q.push(arguments)},
              e[n].q=e[n].q||[];
              var a=t.getElementsByTagName("head")[0],
                  r=new Date,
                  c="https://cdn.yektanet.com/superscript/lgWlX8zJ/native-no-data-44069/yn_pub.js?v="
                    +r.getFullYear().toString()+"0"+r.getMonth()+"0"+r.getDate()+"0"+r.getHours(),
                  s=t.createElement("link");
              s.rel="preload";
              s.as="script";
              s.href=c;
              a.appendChild(s);
              var l=t.createElement("script");
              l.async=!0;
              l.src=c;
              a.appendChild(l)
            }(window,document,"yektanet");
          `}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
